### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by shindakioku** [f3ath/json-api-document-dart#37]
1) Why you don't use generics?

```dart
Map<String, dynamic> meta
```

2) So many checks on null and write into some variable, like this
```dart
if (meta != null) j['meta'] = meta;
```
I think, you need to create method for this.

```dart
setOrNothing(data, variable, nameOfTheVariable) {
   if(null != variable) data[nameOfTheVariable] = variable;
}

j = setOrNothing(j, meta, 'meta')
``` 

3)   [https://github.com/f3ath/json-api-dart/blob/master/lib/src/data_document.dart#L141](https://github.com/f3ath/json-api-dart/blob/master/lib/src/data_document.dart#L141)

4) [https://github.com/f3ath/json-api-dart/blob/master/lib/src/error_document.dart#L20](https://github.com/f3ath/json-api-dart/blob/master/lib/src/error_document.dart#L20)
Spaces?

5) [https://github.com/f3ath/json-api-dart/blob/master/lib/src/link.dart#L38](https://github.com/f3ath/json-api-dart/blob/master/lib/src/link.dart#L38)
```dart
  static LinkObject fromJson(Map<String, dynamic> json) => LinkObject(json['href'], meta: json['meta']);

```

6) [https://github.com/f3ath/json-api-dart/blob/master/lib/src/meta.dart#L10](https://github.com/f3ath/json-api-dart/blob/master/lib/src/meta.dart#L10)
[https://github.com/f3ath/json-api-dart/blob/master/lib/src/attributes.dart#L12](https://github.com/f3ath/json-api-dart/blob/master/lib/src/attributes.dart#L12)
Same.

7) [https://github.com/f3ath/json-api-dart/blob/master/lib/src/naming.dart#L17](https://github.com/f3ath/json-api-dart/blob/master/lib/src/naming.dart#L17)

Maybe ```{}``` because not on the same lines?
([https://github.com/f3ath/json-api-dart/blob/master/lib/src/relationship.dart#L31](https://github.com/f3ath/json-api-dart/blob/master/lib/src/relationship.dart#L31))

**Comment by f3ath** [comment]
1. Not sure what you mean. I can't use a plain Map class here since Meta is supposed to be immutable. And I didn't want to use Map.unmodifiable either because the latter clearly breaks Liskov Substitution Principle. So I came up with a ReadonlyMap class which sort of mimics the read part of Map interface, but does not formally implement a Map.

2. Agreed to this one. Can probably be achieved with `Map.removeWhere()`

3-7. Not sure what you mean. Formatting is done automatically by dartfmt, I have no control over it.
